### ISSUE TITLE
Create the color picker component

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#12]
<img src="https://user-images.githubusercontent.com/29551766/66234940-eca53180-e6bc-11e9-83c5-079fcb3d9633.png" width="150">

Create a component with the following:
- A title in bold
- An input field
- A square color container that dynamically changes with the inputed hex

Bonus (can be done later on):
- Validates a correct hex value is inputed
- When you click on the color container it opens a color picker.
- When you select a color in the color picker, it updates the component with the selected values.

**Comment by Eshno** [comment]
Would like to take this!

**Comment by geekyrajshri** [comment]
Can you assign me this task?

**Comment by yisselda** [comment]
@Eshno I'll assign it to you since you were the first, let me know if you're still interested.
Also can you tell me if you are implementing the bonus parts?

**Comment by yisselda** [comment]
@geekyrajshri thank you for wanting to contribute! Check back soon for other issues. I'll ping you if there is more to do on related to this issue.

**Comment by Eshno** [comment]
@yisselda It'd make sense to include the bonus parts, so I'll be doing them as well
