### ISSUE TITLE
Create the Dashboard

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#13]
Create the Dashboard component that will contain the other components.
The is a container for the preset themes, image input, color pickers and string input components.

Please discuss here what kind of grid system you plan on using (flexbox for example).

<img width="500" alt="Screen Shot 2019-10-04 at 15 55 50" src="https://user-images.githubusercontent.com/29551766/66236051-7bb34900-e6bf-11e9-8b2b-74151c672a18.png">

**Comment by vxdiazdel** [comment]
Seems like a good use-case for CSS grid to layout the PageContainer 🙃 How do you feel about using styled-components instead of SCSS?

**Comment by yisselda** [comment]
@vxdiazdel yes CSS grid is enough for this layout :)
I don't know styled-components and wanted to keep the stack as simple as possible. What was your motivation behind using that over SCSS?

**Comment by vxdiazdel** [comment]
Ah gotcha that makes sense. All the functionality is essentially the same for both libraries but styled-components helps keep the markup a bit cleaner (no need for class names and all that). I'd like to claim this if that's cool with you though! Do you want separate SCSS files for each component or everything in App.scss?

**Comment by yisselda** [comment]
I've assigned this issue to you, thanks for the quick tested PR! Separate SCSS files would be ideal.
