### ISSUE TITLE
Create String Text Theme Input Comonent

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#14]
![image](https://user-images.githubusercontent.com/29551766/66236354-478c5800-e6c0-11e9-949e-13ca43471f6c.png)

Create an input for the string values.
- Validates that there are 8 comma separated values
- Each value is a valid hex color
- Clicking on the `Copy` button adds the value to the clipboard

**Comment by breno-pereira** [comment]
Can you assign me this?

**Comment by yisselda** [comment]
@breno-pereira Here you go! Let me know if you have any question :)

**Comment by yisselda** [comment]
@breno-pereira Are you still working on this?
