### ISSUE TITLE
Have workspace sidebar be a darker shade of the normal sidebar.

### ISSUE THREAD

**Issue by yutingcxiang** [yisselda/SlackableThemes#16]
<img width="298" alt="Screen Shot 2019-10-04 at 4 21 12 PM" src="https://user-images.githubusercontent.com/31348892/66237409-0184c380-e6c3-11e9-8f31-e73b97e3d390.png">

**Comment by Jc7j** [comment]
I'd like to take this up!

**Comment by yisselda** [comment]
@Jc7j Yes sure! This story is to build the background, with one color as the input, you want the background of to be split in two with the left part darker than the right part. To calculate that color you'll have to subtract from the inputted color.

**Comment by Jc7j** [comment]
@yisselda @yutingcxiang Hi, I've gone ahead and added a workspaceSideBar component and some styling to that new component plus the two exisiting components

**Comment by yisselda** [comment]
New update of slack doesn't have this darker shade! Closing the issue.
