### ISSUE TITLE
Create Image Input Component

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#17]
<img width="504" alt="Screen Shot 2019-10-04 at 16 11 51" src="https://user-images.githubusercontent.com/29551766/66237342-d8fcc980-e6c2-11e9-833d-14deb605ea37.png">

Create an input component to upload an image.
- Opens the file navigator to select an image file.
- Validates that it's an image

Bonus can be done later:
- Can Drag an image
- Can upload from a URL
- Displays uploaded image beneath
- Can upload from Drive
<img width="505" alt="Screen Shot 2019-10-04 at 16 11 45" src="https://user-images.githubusercontent.com/29551766/66237620-85d74680-e6c3-11e9-9b6b-d96d3eb8004d.png">

**Comment by amolmt** [comment]
I'd like to help. Assign this to me if possible.

**Comment by yisselda** [comment]
@amolmt Here you go. Let me know if you have any question!

**Comment by yisselda** [comment]
@amolmt Do you still want to work on this?
