### ISSUE TITLE
Create Preset Themes

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#19]
<img width="518" alt="Screen Shot 2019-10-04 at 16 26 59" src="https://user-images.githubusercontent.com/29551766/66237729-d77fd100-e6c3-11e9-8554-27b6395ba6f5.png">

Create the Preset Theme component:
- It dynamically changes depending on the hex colors passed as props.
- It is associated with a hardcoded theme
- It can be selected

**Comment by macanrox** [comment]
Can I take this?

**Comment by yisselda** [comment]
@macanrox Here you go! Let me know if you have any question :)

**Comment by macanrox** [comment]
### Hello, here's an update! :raised_hands: 
The changes can be viewed over at [my forked repo](https://github.com/macanrox/SlackableThemes/tree/feature/preset-themes)

**Also let me know if there are any changes you'd like me to make. I'll be waiting on making the PR until I generate unit tests.**

### To Do

- [x] Create Preset Theme component 
   - [x] It dynamically changes depending on the hex colors passed as props.
   - [x] It is associated with a hardcoded theme
   - [x] It can be selected

- [ ] Create unit tests

### About the Preset Theme component

- Created data for the hardcoded themes in `data/preset-themes.js`
- Images preview of the themes are in `public/images`
- The colors are stored in a state as an array in `PageContainer.js` and get updated whenever `PresetThemes.js` is selected

**Comment by yisselda** [comment]
@macanrox Thank you for contributing !!! 🎉
