### ISSUE TITLE
Create The Slack Sidebar

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#21]
Create the interactive Sidebar

<img width="1423" alt="SlackableThemesMockUp" src="https://user-images.githubusercontent.com/29551766/66239013-cdab9d00-e6c6-11e9-92b0-ecc9d0797d94.png">

- It has the same interaction as the slack side bar (selects and hovers)
- It takes hex colors as props to easily change the colors of the different elements.

**Comment by nik72619c** [comment]
can I work on this ?

**Comment by yutingcxiang** [comment]
@nik72619c The majority of the sidebar has been implemented but if you would like to finish it off, please do! The last part is passing down the theme prop from the PageContainer and dynamically adjusting each portion of the sidebar as the theme changes. Thanks!

**Comment by nik72619c** [comment]
okay, will do

**Comment by yutingcxiang** [comment]
Thanks for handling this!

**Comment by nik72619c** [comment]
Is there any work being done on the theme part or do i have to write the code for changing the theme of the sidebar ?

**Comment by nik72619c** [comment]
I mean is there a mechanism for changing the style as per the theme supplied as a prop or do I need to work on that as well ?

**Comment by yutingcxiang** [comment]
There currently is not. I started working on this by adding a default theme (aubergine) in PageContainer.js, passing it down to SideBar as a prop and then changing the colors in the SideBar component using inline styles. You can checkout my default-theme branch if you want to continue with what I have or feel free to implement it your own way if you have another method in mind.

**Comment by nik72619c** [comment]
So basically is it just changing the background or is it about changing the background along with the text (the text in the sense the one which is white right now) ?

**Comment by yutingcxiang** [comment]
The background, font and parts of the sidebar will change on hover or on active as well. Check out the themes section in Slack to see specifically how components change.
