### ISSUE TITLE
Update deprecated packages

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#31]
**Describe the bug**
Update deprecated packages to maintain the app the most up to date as possible.

**To Reproduce**
When running `npm i` you'll see the list of deprecated packages.

**Screenshots**
![image](https://user-images.githubusercontent.com/29551766/66436620-863e4d00-e9f5-11e9-9047-abd27628a66d.png)

**Comment by deepansh946** [comment]
@yisselda I would like to work on this.

**Comment by yisselda** [comment]
@deepansh946 Yes thanks! I’ll assign it to you.

**Comment by yisselda** [comment]
@deepansh946 Thank you for contributing! 🎉
