### ISSUE TITLE
Pick yarn or npm and include relevant lockfile.

### ISSUE THREAD

**Issue by tvandort** [yisselda/SlackableThemes#32]
## Is your feature request related to a problem? Please describe.
Having both yarn and npm supported means that during PRs contributors would in theory have to both `yarn add <package>` and `npm install <package>` for a dependency to appear in both lockfiles.

## Describe the solution you'd like
Pick between yarn or npm. I have a strong preference for yarn due to historic consistency in restoring packages for users, where often npm produces different package-locks for different users even on the same version of npm (in my experience).

Yarn also has some features that npm still lacks such as [resolutions](https://yarnpkg.com/en/docs/package-json#toc-resolutions) which has gotten me out of sticky dependency situations before.

For those familiar with npm, yarns commands are slightly different but have simple 1-to-1 translations.

## Describe alternatives you've considered
Use npm. It's the default, more people seem familiar with it.

**Comment by yisselda** [comment]
@tvandort Thanks for bringing that up. Didn't really think of the issue of having both before. Giving the possibility of both yarn and npm means the lock files could be out of sync.
Let's use npm since it's the most common.
Don't you need a last PR for Hacktoberfest ^^?
