### ISSUE TITLE
Add mention badge to the sidebar and configure it to change color depending on theme.

### ISSUE THREAD

**Issue by yutingcxiang** [yisselda/SlackableThemes#34]
Add the mention badge to the SideBar.js component and ensure it receives the proper props to change color in relation to the current theme. 

<img width="214" alt="mention-badge" src="https://user-images.githubusercontent.com/31348892/66579585-0924ec00-eb4b-11e9-9597-2758b096b2fc.png">
<img width="161" alt="mention-badge-color" src="https://user-images.githubusercontent.com/31348892/66579589-0aeeaf80-eb4b-11e9-97f1-01cade207a0e.png">

**Comment by r4zorgeek** [comment]
@yutingcxiang Hey can I take this issue?

**Comment by yutingcxiang** [comment]
Of course, thanks for handling this!

**Comment by yisselda** [comment]
@r4zorgeek Do you still want to work on this?
