### ISSUE TITLE
Implement copy functionality for color-input 

### ISSUE THREAD

**Issue by yutingcxiang** [yisselda/SlackableThemes#47]
Add functionality so the 'Copy' button for the custom theme allows it to be copied elsewhere. 

<img width="607" alt="Screen Shot 2019-11-27 at 11 30 08 AM" src="https://user-images.githubusercontent.com/31348892/69741716-8a3f3f00-1109-11ea-9050-201a546c24ae.png">

**Comment by yisselda** [comment]
@yutingcxiang Thanks I was going to add it after I saw your PR :)
