### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#51]
Now that slack supports Dark Mode

### Light 🌞- 🌚 Dark 
We want to add a toggle to switch from Light Theme to Dark Theme.
I'm open to design suggestions.

### Black-ish background for the Dashboard
HEX: #1D1A21 
RGB: 26,29,33
And the text color is white.

### Add the specific Preset Themes
The preset themes have their Dark Side counterparts.
We need to add them and display those instead when we switch the mode.

**Comment by stephjs** [comment]
Hi @yisselda I have an open [PR](https://github.com/yisselda/SlackableThemes/pull/108) to add dark mode.
