### ISSUE TITLE
Limit file types that can be uploaded

### ISSUE THREAD

**Issue by yutingcxiang** [yisselda/SlackableThemes#75]
Limit the accepted file types to be images (.png, .jpeg, .pdf, .gif) for the image uploader.

**Comment by yisselda** [comment]
Linked issue https://github.com/yisselda/SlackableThemes/issues/83#issue-608743612

**Comment by stephjs** [comment]
Hey @yisselda and @yutingcxiang I submitted a [PR](https://github.com/yisselda/SlackableThemes/pull/114) for this issue 😊
