### ISSUE TITLE
Copy doesn’t work on mobile 

### ISSUE THREAD

**Issue by yisselda** [yisselda/SlackableThemes#92]
When on mobile, the copy button’s style doesn’t work and doesn’t copy the values to the clipboard.

I tried in Chrome, on an IPhone 8, iOS 13.4.1

![92AD523A-BB36-4A6B-89C6-66EC0A737BDD](https://user-images.githubusercontent.com/29551766/80846931-df610e80-8bdb-11ea-9628-8ea157fe23ff.png)

**Comment by kallir** [comment]
Pull request #93 might fix this !

**Comment by yisselda** [comment]
@kallir the copy functionality works 👍but the animation to "Copied!" doesn't show.
I think it's fine and it resolves the bug.
